// XTPDockingPaneResource.h
//
// This file is a part of the XTREME TOOLKIT PRO MFC class library.
// ©1998-2005 Codejock Software, All Rights Reserved.
//
// THIS SOURCE FILE IS THE PROPERTY OF CODEJOCK SOFTWARE AND IS NOT TO BE
// RE-DISTRIBUTED BY ANY MEANS WHATSOEVER WITHOUT THE EXPRESSED WRITTEN
// CONSENT OF CODEJOCK SOFTWARE.
//
// THIS SOURCE CODE CAN ONLY BE USED UNDER THE TERMS AND CONDITIONS OUTLINED
// IN THE XTREME TOOLKIT PRO LICENSE AGREEMENT. CODEJOCK SOFTWARE GRANTS TO
// YOU (ONE SOFTWARE DEVELOPER) THE LIMITED RIGHT TO USE THIS SOFTWARE ON A
// SINGLE COMPUTER.
//
// CONTACT INFORMATION:
// support@codejock.com
// http://www.codejock.com
//
/////////////////////////////////////////////////////////////////////////////

#define XTP_IDS_DOCKINGPANE_AUTOHIDE           9900
#define XTP_IDS_DOCKINGPANE_CLOSE              9901
#define XTP_IDB_DOCKINGPANE_VISIOGRIPPER       9902
#define XTP_IDB_DOCKINGPANE_STICKER_CLIENT     9903
#define XTP_IDB_DOCKINGPANE_STICKERS_BLUE      9904
#define XTP_IDB_DOCKINGPANE_STICKERS_OLIVE     9905
#define XTP_IDB_DOCKINGPANE_STICKERS_SILVER    9906
